#!/bin/sh
echo $1
if [ "$1" = "H" ]; then
    tmux new-session \; \
        send-keys 'watch -n 2 sensors' C-m \; \
        split-window -h -p 50 \; \
        send-keys 'htop' C-m \; \
        split-window -v -p 50 \; \
        send-keys 'nvtop' C-m \;
else
    tmux new-session \; \
        split-window -v -p 75 \; \
        send-keys 'htop' C-m \; \
        split-window -v -p 67 \; \
        send-keys 'nvtop' C-m \; \
        split-window -v -p 50 \; \
        send-keys 'watch -n 2 sensors' C-m \;
fi
